name: style checking

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # Stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings, max-complexity is set to 10, max-line-length is set to 127
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics \
          --exclude=migrations,mysite \
          --per-file-ignores="models.py:E501" \  # Allow longer lines in models.py (up to 100 chars)
          --ignore=D107,D105  # Ignore missing docstrings in __init__.py (D107), __main__.py (D105)
