name: Lint with Flake8

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 flake8-docstrings
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint tests and views with flake8
      run: |
        flake8 polls/tests polls/views.py --count --statistics --exclude __init__.py
    - name: Lint models with flake8
      run: |
        flake8 polls/models.py --count --statistics --max-line-length=100
